#!/usr/bin/env python3

from lunar.find_contours import find_contours_from_videos
from lunar.plot_contours import plot_contours

# Define the arguments
video_pattern = '/Users/oakley/Downloads/out_03.mp4'
output_suffix = '22Jul2024.tsv'
black_threshold = 200
min_area = 15
max_area = 1000
brightness_threshold = 100

# Call the function to process videos and generate the output file
find_contours_from_videos(
    video_pattern=video_pattern,
    black=black_threshold,
    minArea=min_area,
    maxArea=max_area,
    brightnessThreshold=brightness_threshold,
    threads=2,  # Adjust the number of threads as needed
    outfile=output_suffix
)

# Define the path to the output file from the previous step
output_file = 'contours_' + output_suffix

# Plot the contours data
plot_contours(output_file)

